dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - cmake

script:
 - mkdir build
 - cd build
 - cmake -DAABB_BUILD_TESTS=ON ..
 - make
 - make test
