image:
  - Visual Studio 2017
build_script:
- cmd: >-
    git submodule update --init

    mkdir build

    cd build

    cmake -DAABB_BUILD_TESTS=ON -Dgtest_force_shared_crt=ON .. -G "Visual Studio 15"

    cmake --build . --config "Debug"

    ctest
